apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-reader
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-reader-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-reader-binding
subjects:
  - kind: ServiceAccount
    name: cluster-reader
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-reader-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: sa-test-pod
  namespace: default
spec:
  serviceAccountName: cluster-reader
  containers:
    - name: curl-container
      image: curlimages/curl:latest
      command: ["sleep", "3600"]